### ISSUE TITLE
Data formatting for Graphite

### ISSUE THREAD

**Issue by gmihaiescu** [Crapworks/ceph-dash#11]
Thank you for the ceph dashboard, it works great.
I also  tried to implement the Graphite but how do you mutate the output of check-ceph-dash.py --url 'http://url/' and prepare it for graphite? I collect the data with Sensu which then should relay it to Graphite.

My output is below and it's not ready for Graphite:

WARNING: HEALTH_WARN: 326 pgs backfill
HEALTH_WARN: 7 pgs backfilling
HEALTH_WARN: 333 pgs stuck unclean
HEALTH_WARN: recovery 3886019/6281616 objects misplaced (61.863%)|bytes_total=71977097650176 num_pgs=3008 data_bytes=9291449512727 bytes_used=18667776380928 num_osds=18 op_per_sec=0 num_up_osds=18 num_in_osds=18 read_bytes_sec=0 write_bytes_sec=0 bytes_avail=53309321269248

Thank you.

**Comment by gmihaiescu** [comment]
Never mind, I got it working by adding a timestamp and piping to  "xargs -n3".

**Comment by Crapworks** [comment]
Hi gmihaiescu,

check-ceph-dash is a nagios plugin and produces output that Nagios and Icinga can understand. The data behind the pipe is handled as "perfdata" by Nagios like monitoring systems. I was just checking because I thought that Sensu can invoke Nagios checks as well. It can indeed, but obviously only Sensu Enterprise can process the perfdata potion returned by those checks.

So your approach was the right one in this case :)

Regards,
Chriszian
