### ISSUE TITLE
read and write MB/sec not correct

### ISSUE THREAD

**Issue by tdeneau** [Crapworks/ceph-dash#16]
I am trying to set up a single-node demo system for someone and am using the ceph-dash as a visual indicator (definitely the easiest ceph dashboard to get running!)
I am running separate rados bench read and write processes and I have noticed the MB/sec for reads and writes is often twice as big as the actual numbers reported by rados bench.

Now I am running rados bench on the same node where the osds reside, would that be causing the problem?

Also, in a related issue, with the above configuration of rados bench running on the same node, the reads/sec is often shown as zero.

**Comment by Crapworks** [comment]
Hi tdeneau,

this is not an issue of ceph-dash. Ceph-dash just outputs the same data as shown on the command line via ```ceph status```. Since it is only refreshing every 5 seconds, it can only show a current snaphot of the overall cluster performance. The rados benchmark for sure shows you the acutal data rates librados is able to write and read.

So this is actually not an error, it is just the nature of how the ceph cluster is showing its performance statistics.

Regards,
Christian

**Comment by tdeneau** [comment]
Thanks, I did not realize that ceph status provided this information, will look into how it computes it
