### ISSUE TITLE
The ceph-dash don't get data from the ceph cluster on centos 6.5

### ISSUE THREAD

**Issue by mtanlee** [Crapworks/ceph-dash#18]
II don't know the reason. My configure:
sudo cat config.json 
{
   "ceph_config": "/etc/ceph/ceph.conf",
   "keyring": "/etc/ceph/admin.keyring",
   "client_name": "client.admin",
   "graphite": {
        "url": "http://graphite.server.org",
        "metrics": [
            {
                "targets": [ 
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.read_bytes_sec)",
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.write_bytes_sec)"
                ],
                "labels": [ "Read", "Write" ],
                "from": "-2h",
                "mode": "byteRate"
            },
            {
                "targets": [ 
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.op_per_sec)"
                ],
                "labels": [ "IOPS" ],
                "colors": [ "#5bc0de" ],
                "from": "-2h"
            }
        ]
    }

}

**Comment by Crapworks** [comment]
Hi mtanlee,

well, that can have a lot of reasons. With that amount of information I can't tell you where the problem is.

Do you run ceph-dash in a web server or jsut starting it on the command line? As which user? Do the mentioned config files exist and are readable for the current user?

Looks like you just took the sample config file and used it. You have to insert values that are suitable for YOUR environment, otherwise it will not work.

**Comment by mtanlee** [comment]
Hi Crapworks ,
  thanks,this is my  negligence.The root run ceph-dash on the command line.
  I try againt.

**Comment by Crapworks** [comment]
Looks like this can be closed :)
