### ISSUE TITLE
SSE/WebSocket support?

### ISSUE THREAD

**Issue by LenzGr** [Crapworks/ceph-dash#27]
This is more an enhancement idea than a bug report - currently, the Web application seems to poll the server application for updates every 5 seconds. Have you considered using [Server-Sent Events (SSE) or WebSockets](http://www.html5rocks.com/en/tutorials/eventsource/basics/) instead? This might give the app a more "real-time" feeling and would avoid the polling.

**Comment by Crapworks** [comment]
Hi Lenz,
SSE and Websockets are a cool thing when you have an event-driven backend. For ceph-dash, this is not the case. The backend (the flask-application) hast to actively pull the current statistics from the ceph backend. The arbitrary (and changable) 5 seconds interval can't be replaced by an event, because the is no event. 
It is a cool Idea and I was playing around with websockets in other projects, but using it in the (javascript) frontend wouldn't be of much use since the (python) backend would still have an (now invisible) interval for pulling data from the ceph cluster.
Regards,
Christian

**Comment by LenzGr** [comment]
Thanks for the explanation. I agree, there isn't really an "event" that would need to be triggered via the backend to result in a change of the frontend. I was more thinking about the additional latency and round-trips of polling the backend vs. keeping a connection open and letting the backend stream updates to the frontend as soon as it has retrieved them. Our [project](http://openattic.org/) uses a similar approach for displaying usage statistics for network and disk utilization via a dedicated web app ([serverstats.wsgi](https://bitbucket.org/openattic/openattic/src/169f69a055677ce6acbe9d077f9e0cc82850e955/backend/serverstats.wsgi?at=default&fileviewer=file-view-default))

**Comment by Crapworks** [comment]
I just checked the WSGI app you mentioned. Well, in my oppinion a web-services, especially one who, like ceph-dash, provides a REST api should be stateless. The extremely small overhead of having a AJAX request every 5 seconds that returns a few kilobyte of Javascript doesn't justify the code-overhead of implementing websocket technology. It is just not the right tool for a REST api/jQuery web gui. 
Ceph-dash is quite a simple and small piece of code and I'd like to keep it that way. That is, in my oppinion, the biggest advantage to full blown management interfaces like Calamary.

**Comment by LenzGr** [comment]
Makes sense. Thanks for the reply! I'll close this request then, if you don't mind.
