### ISSUE TITLE
Couldn't display performance metrics

### ISSUE THREAD

**Issue by Henryballs** [Crapworks/ceph-dash#31]
Hi Chris,

I'm trying to use ceph-dash to monitor the performance of my cepy-cluster. I followed the instructions to deploy the ceph-dash, but couldn't display the performance mertics. below is my config.json:
{
    "ceph_config": "/etc/ceph/ceph.conf",
    "graphite": {
        "url": "http://xxx.xxx.28.10:8080",
        "metrics": [
            {
                "targets": [
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.read_bytes_sec)",
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.write_bytes_sec)"
                ],
                "labels": [ "Read", "Write" ],
                "from": "-2h",
                "mode": "byteRate"
            },
            {
                "targets": [
                    "avg(monitoring.ceph-mon*.ceph_overall_cluster_status.op_per_sec)"
                ],
                "labels": [ "IOPS" ],
                "colors": [ "#5bc0de" ],
                "from": "-2h"
            }
        ]
    }
}
 I also couldn't open http://xxx.xxx.28.10:8080/render?target=monitoring.ceph-mon0.ceph_overall_cluster_status.read_bytes_sec.

would you please tell me where is wrong and how can I correct it?

thanks so much.

**Comment by Crapworks** [comment]
Hi @Henryballs,

Well, the problem seems to be that you graphite has no data at the specified target. Like I was trying to explain in the Readme is that ceph-dash does not put any data into graphite or influxdb. It literally can't, because it is not a server, just a WSGI app.

How are you getting your data into graphite? Because if you don't have a mechanism that gathers data and put it into you graphite cluster, this is not going to work.

Regards,
Christian

**Comment by Crapworks** [comment]
I am going to close this now, since no reply.
