### ISSUE TITLE
[apache2] can't get ceph-dash to work with Apache/2.4.18

### ISSUE THREAD

**Issue by ghost** [Crapworks/ceph-dash#38]
Hi,

I'm running Apache/2.4.18 and Ubuntu 16.04.1.

I followed the 'tutorial', using the /opt/ceph-dash/contrib/apache/cephdash file, but I get the error:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

My /etc/apache2/sites-enabled/cephdash is currently this:

```
<VirtualHost *:80>
    ServerName dash.ceph.enterprise.com

    WSGIDaemonProcess cephdash user=www-data group=www-data processes=1 threads=5
    WSGIScriptAlias / /opt/ceph-dash/contrib/wsgi/cephdash.wsgi
    WSGIPassAuthorization On

    <Directory /opt/ceph-dash>
        WSGIProcessGroup cephdash
        WSGIApplicationGroup %{GLOBAL}
        Require all granted
    </Directory>
</VirtualHost>
```

Apache logs don't show anything. All files under the /opt/ceph-dash have the proper permissions (www-data:www-data).

Everything works fine when running the application through the **/opt/ceph-dash/ceph-dash.py** Flask script.

When replacing the "Require all granted" in the apache vhost configuration to the old style: 

```
        Order deny,allow
        Allow from all
```

the apache error.log returns this:

> [Mon Sep 26 16:23:14.161427 2016] [authz_core:error] [pid 18290:tid 140571006453504] [client 172.30.50.14:49856] AH01630: client denied by server configuration: /opt/ceph-dash/contrib/wsgi/cephdash.wsgi

My libapache2-mod-wsgi is currently in version 4.3.0-1.1build1.

Any tips regarding this?

**Comment by romerojnr** [comment]
I have just swapped to Nginx, and I have the same error, and nothing on the logs.

**Comment by Crapworks** [comment]
It is really hard for me to tell what the poblem could be from remote. In my experience for an Internal Server Error, there should be something in the error log. Since you are not the only one who is encountering this kind of errors, I am trying to test it myself on a VM tomorrow. Maybe I will find something.

Can you please tell me the versions of the python extensions of Flask and the python-ceph bindings and how you've installed them?

**Comment by hansbogert** [comment]
Did you install and activate the wsgi module for apache?

**Comment by Kaeltis** [comment]
Have the same problem, added the following to ceph-dash/contrib/wsgi/cephdash.wsgi, which allows errors to be shown in the apache error log:

`import logging, sys`
`logging.basicConfig(stream=sys.stderr)`

Shows the following error, I guess it's because the apache user not having the permissions to connect:

> [Sat Nov 26 20:35:43.944438 2016] [:error] [pid 6568] ERROR:app:Exception on / [GET]
[Sat Nov 26 20:35:43.944466 2016] [:error] [pid 6568] Traceback (most recent call last):
[Sat Nov 26 20:35:43.944468 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Sat Nov 26 20:35:43.944470 2016] [:error] [pid 6568]     response = self.full_dispatch_request()
[Sat Nov 26 20:35:43.944472 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Sat Nov 26 20:35:43.944474 2016] [:error] [pid 6568]     rv = self.handle_user_exception(e)
[Sat Nov 26 20:35:43.944476 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Sat Nov 26 20:35:43.944477 2016] [:error] [pid 6568]     reraise(exc_type, exc_value, tb)
[Sat Nov 26 20:35:43.944479 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Sat Nov 26 20:35:43.944481 2016] [:error] [pid 6568]     rv = self.dispatch_request()
[Sat Nov 26 20:35:43.944482 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Sat Nov 26 20:35:43.944484 2016] [:error] [pid 6568]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Nov 26 20:35:43.944486 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
[Sat Nov 26 20:35:43.944488 2016] [:error] [pid 6568]     return self.dispatch_request(*args, **kwargs)
[Sat Nov 26 20:35:43.944490 2016] [:error] [pid 6568]   File "/usr/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
[Sat Nov 26 20:35:43.944491 2016] [:error] [pid 6568]     return meth(*args, **kwargs)
[Sat Nov 26 20:35:43.944493 2016] [:error] [pid 6568]   File "/var/www/html/ceph-dash/contrib/wsgi/../../app/dashboard/views.py", line 112, in get
[Sat Nov 26 20:35:43.944506 2016] [:error] [pid 6568]     with Rados(**self.clusterprop) as cluster:
[Sat Nov 26 20:35:43.944508 2016] [:error] [pid 6568]   File "rados.pyx", line 595, in rados.Rados.__enter__ (rados.c:6875)
[Sat Nov 26 20:35:43.944510 2016] [:error] [pid 6568]   File "rados.pyx", line 785, in rados.Rados.connect (rados.c:8969)
[Sat Nov 26 20:35:43.944512 2016] [:error] [pid 6568] ObjectNotFound: error connecting to the cluster

**Comment by Crapworks** [comment]
Hi @Kaeltis 

Ceph-Dash already has these options: 
https://github.com/Crapworks/ceph-dash#user-content-deployment

Regards,
Christian

**Comment by Crapworks** [comment]
@ghost were you able to get it running? can I close this isse?
